use_frameworks!

platform :ios, '9.0'

target 'LibDynamicFrameworkA_Example' do
  pod 'LibDynamicFrameworkA', :path => '../'

  target 'LibDynamicFrameworkA_Tests' do
    inherit! :search_paths

    
  end
end
