use_frameworks!

platform :ios, '9.0'

target 'LibDynamicFrameworkB_Example' do
  pod 'LibDynamicFrameworkB', :path => '../'

  target 'LibDynamicFrameworkB_Tests' do
    inherit! :search_paths

    
  end
end
